### ISSUE TITLE
Change "editable" join tables to versioned records

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/marine-defrag-server#92]
Specifically the relevant tables are:

* actor_categories
* measure_categories
* memberships
* measure_resource
* user_role

**Comment by tmfrnz** [comment]
@parndt happy to do it myself if this is as easy as changing the first line in the respective model files from eg "class MeasureResource < ApplicationRecord" to "class MeasureResource < VersionedRecord". Thanks for confirming =)

**Comment by parndt** [comment]
@tmfrnz not quite that simple 😄 will open a PR

**Comment by parndt** [comment]
@tmfrnz it's a bit confusing though because these tables aren't editable

measure_categories CRD #27
actor_categories CRD #24 
memberships CRD #19 
measure_resources CRD #30 
user_roles #36 

So all of their policies etc won't allow this. See PR #92 for the implementation so far. It will need updating to change the policy files for each join table that can now allow updates, as well as extra test cases added to their controller specs if we want to make this change.  Let me know if you want that 😄
